name: Deploy workflow
on: [push, pull_request]
jobs:
  tests:
    name: tests
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: phpunit, phpstan
          extensions: json, mbstring, sqlsrv, pdo_sqlsrv, xdebug

      - name: Install dependencies
        run: composer install

      - name: Unit test
        continue-on-error: true
        run: |
          phpunit --coverage-text

      - name: Static Analysis
        continue-on-error: true
        run: |
          phpstan analyse --no-progress Controllers
          phpstan analyse --no-progress Models
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Deploy files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ SECRETS.host }}
          username: ${{ SECRETS.username }}
          key: ${{ SECRETS.sshkey }}
          script: |
            cd /var/www/sqlapp
            sudo git pull -f https://Bharani-Schawk:${{ SECRETS.GITHUB_TOKEN }}@github.com/Bharani-Schawk/php-7-ms-sql-server.git HEAD:master
            sudo git log